version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 18
  pre-install:
    commands:
      - cd my-app
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm test

artifacts:
  files:
    - '**/*'
    # - "my-app/build/**/*"
  base-directory: 'my-app/build'
  discard-paths: yes
